package dk.trustworks.userservice.repositories;

import dk.trustworks.userservice.model.UserContactinfo;
import io.reactivex.Single;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.reactivex.ext.jdbc.JDBCClient;
import io.vertx.reactivex.ext.sql.SQLConnection;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.stream.Collectors;

public class ContactInfoRepository {

    private JDBCClient jdbc;

    public ContactInfoRepository(JDBCClient jdbc) {
        this.jdbc = jdbc;
    }

    private Single<SQLConnection> connect() {
        return jdbc.rxGetConnection()
                .map(c -> c.setOptions(new SQLOptions().setAutoGeneratedKeys(true)));
    }

    private Single<List<UserContactinfo>> query(SQLConnection connection) {
        return connection.rxQuery("SELECT * FROM user_contactinfo")
                .map(rs -> rs.getRows().stream().map(UserContactinfo::new).collect(Collectors.toList()))
                .doFinally(connection::close);
    }

    private Single<UserContactinfo> queryByUser(SQLConnection connection, String userUUID) {
        String sql = "SELECT * FROM user_contactinfo where useruuid LIKE ?";
        return connection.rxQueryWithParams(sql, new JsonArray().add(userUUID))
                .doFinally(connection::close)
                .map(rs -> {
                    List<JsonObject> rows = rs.getRows();
                    if (rows.size() == 0) {
                        throw new NoSuchElementException("No contactinfo with useruuid " + userUUID);
                    } else {
                        JsonObject row = rows.get(0);
                        return new UserContactinfo(row);
                    }
                });
    }

    private Single<UserContactinfo> queryOne(SQLConnection connection, String uuid) {
        String sql = "SELECT * FROM user_contactinfo WHERE uuid LIKE ?";
        return connection.rxQueryWithParams(sql, new JsonArray().add(uuid))
                .doFinally(connection::close)
                .map(rs -> {
                    List<JsonObject> rows = rs.getRows();
                    if (rows.size() == 0) {
                        throw new NoSuchElementException("No role with id " + uuid);
                    } else {
                        JsonObject row = rows.get(0);
                        return new UserContactinfo(row);
                    }
                });
    }

    public Single<List<UserContactinfo>> getAllContactInfos() {
        return connect().flatMap(this::query);
    }

    public Single<UserContactinfo> getUserContactInfo(String userUUID) {
        return connect().flatMap((SQLConnection connection) -> queryByUser(connection, userUUID));
    }

    public Single<UserContactinfo> getOne(String uuid) {
        return connect().flatMap(connection -> queryOne(connection, uuid));
    }
}
