package dk.trustworks.userservice.repositories;

import dk.trustworks.userservice.model.Role;
import io.reactivex.Completable;
import io.reactivex.Single;
import io.vertx.core.json.JsonArray;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.reactivex.ext.jdbc.JDBCClient;
import io.vertx.reactivex.ext.sql.SQLConnection;

import java.util.NoSuchElementException;

/**
 * http://localhost:5460/users/7948c5e8-162c-4053-b905-0f59a21d7746/roles/type/ADMIN
 */

public class RoleRepository {

    private JDBCClient jdbc;

    public RoleRepository(JDBCClient jdbc) {
        this.jdbc = jdbc;
    }

    private Single<SQLConnection> connect() {
        return jdbc.rxGetConnection()
                .map(c -> c.setOptions(new SQLOptions().setAutoGeneratedKeys(true)));
    }

    public Completable create(String useruuid, Role role) {
        return connect().flatMapCompletable(connection -> {
            String sql = "INSERT INTO usermanager.roles " +
                    "(uuid, useruuid, role) " +
                    "VALUES " +
                    "(?, ?, ?);";
            JsonArray params = new JsonArray()
                    .add(role.getUuid())
                    .add(useruuid)
                    .add(role.getRole().name());
            return connection.rxUpdateWithParams(sql, params)
                    .flatMapCompletable(ur ->
                            ur.getUpdated() == 0 ?
                                    Completable.error(new NoSuchElementException("No user with uuid " + useruuid))
                                    : Completable.complete()
                    )
                    .doFinally(connection::close);
        });
    }

    public Completable delete(String useruuid) {
        System.out.println("RoleRepository.delete");
        System.out.println("useruuid = " + useruuid);
        return connect().flatMapCompletable(connection -> {
                String sql = "DELETE FROM usermanager.roles WHERE useruuid LIKE ?;";
            JsonArray params = new JsonArray().add(useruuid);
            return connection.rxUpdateWithParams(sql, params)
                    .flatMapCompletable(ur ->
                            Completable.complete()
                    )
                    .doFinally(connection::close);
        });
    }

/*
    public Completable create(String useruuid, Role role) {
        return connect().flatMapCompletable(connection -> {
            String sql = "INSERT INTO usermanager.salary " +
                    "(uuid, useruuid, salary, activefrom) " +
                    "VALUES " +
                    "(?, ?, ?, ?);";
            JsonArray params = new JsonArray()
                    .add(salary.getUuid())
                    .add(useruuid)
                    .add(salary.getSalary())
                    .add(salary.getActivefrom().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
            return connection.rxUpdateWithParams(sql, params)
                    .flatMapCompletable(ur ->
                            ur.getUpdated() == 0 ?
                                    Completable.error(new NoSuchElementException("No user with uuid " + useruuid))
                                    : Completable.complete()
                    )
                    .doFinally(connection::close);
        });
    }

    public Completable delete(String salaryuuid) {
        System.out.println("SalaryRepository.delete");
        System.out.println("salaryuuid = " + salaryuuid);
        return connect().flatMapCompletable(connection -> {
            String sql = "DELETE FROM usermanager.salary WHERE uuid LIKE ?;";
            System.out.println("sql = " + sql);
            JsonArray params = new JsonArray().add(salaryuuid);
            System.out.println("salaryuuid = " + salaryuuid);
            return connection.rxUpdateWithParams(sql, params)
                    .flatMapCompletable(ur ->
                            ur.getUpdated() == 0 ?
                                    Completable.error(new NoSuchElementException("No salary with uuid " + salaryuuid))
                                    : Completable.complete()
                    )
                    .doFinally(connection::close);
        });
    }

 */
}
